version: '3.8'

services:
  municorn-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=54\
        28;Database=municorn;Username=postgres;Password=postgres"
    depends_on:
      - municorn-db

  municorn-db:
    image: postgres:latest
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: municorn
    command: "-c log_statement=all"
